### ISSUE TITLE
Requests fall off before the container is created

### ISSUE THREAD

**Issue by mike-petrov** [nspcc-dev/panel-fs-neo-org#62] opened 2022-10-20 09:58 UTC
The frontend does not receive a response about the successful or unsuccessful creation of the container, so the application cannot understand the status and crashes with an error.

<img width="636" alt="image" src="https://user-images.githubusercontent.com/32885629/196917610-a99897c1-a2b8-4e63-a3a1-a94290b5a9b0.png">

We need to understand which side the problem is on:
- response does not come from the rest gate
- creating a container takes longer than waiting for a response. In this case, we need to understand where to increase timeouts: at the frontend or backend

**Comment by masterSplinter01** [comment] 2022-11-30 10:52
@mike-petrov  and I couldn't reproduce it, I propose to close the issue. If the error appears again, we will reopen it.

**Closed** 2022-11-30 14:25 UTC
Labels: P1, 2022Q4
